### ISSUE TITLE
Transfer to emacs-dashboard organization?

### ISSUE THREAD

**Issue by jcs090218** [emacs-dashboard/dashboard-ls#1]
@JesusMtnez Would you mind if I transfer this package/repository to organization `emacs-dashboard`?

This is a simple plugin that shows the current directories/files with dashboard.

**Comment by JesusMtnez** [comment]
Of course!! Let me know if there is anything I could help.

**Comment by jcs090218** [comment]
Thanks! I appreciated! 👍
